---
title: "projet eco"
output: html_document
date: "2026-04-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
p_load <- pacman::p_load
p_load(readr)            #pour importer nos données
p_load(tidyverse)        #pour les fonctions essentielles (ggplot,...)
p_load(questionr)        #pour les tables statistiques
p_load(Epi)              #pour les tables statistiques aussi
p_load(vtable)           #pour de meilleures tables statistiques
p_load(patchwork)        #c'est pour mieux présenter les graphiques, il laisse plus de choix que simplement grid.arrange()
```
```{r file csv}
teen_addiction <- "https://raw.githubusercontent.com/insseuv/projet-conom-trie/refs/heads/main/teen_phone_addiction_dataset.csv?token=GHSAT0AAAAAAD3SQCDDBXSLI5PNBHODXSOW2PPGE5Q"
teens <- read_csv(teen_addiction)
#important : inverser ou doubler les backslashs  
#faudra ajuster le chemin d'accès pour chaque machine

#petite vue d'ensemble des données (glimpse) avec un résumé rapide de chaque variable (summary) 
glimpse(teens)
summary(teens)

```
