---
title: "projet eco"
output: html_document
date: "2026-04-27"
---

```{r packages}
p_load <- pacman::p_load
p_load(readr)            #pour importer nos données
p_load(tidyverse)        #pour les fonctions essentielles (ggplot,...)
p_load(questionr)        #pour les tables statistiques
p_load(Epi)              #pour les tables statistiques aussi
p_load(vtable)           #pour de meilleures tables statistiques
p_load(patchwork)        #c'est pour mieux présenter les graphiques, il laisse plus de choix que simplement grid.arrange()
p_load(ggplot2)
p_load(e1071) # Pour l'asymétrie et l'aplatissement
```
```{r file csv}
teen_addiction <- "https://raw.githubusercontent.com/insseuv/projet-conom-trie/refs/heads/main/teen_phone_addiction_dataset.csv?token=GHSAT0AAAAAAD3SQCDDBXSLI5PNBHODXSOW2PPGE5Q" #lien à adapter jsp trop comment le mettre pour le rendre
teens <- read_csv(teen_addiction)
#important : inverser ou doubler les backslashs  
#faudra ajuster le chemin d'accès pour chaque machine

```


```{r affichage données}
head(teens)
glimpse(teens)
summary(teens)
#petite vue d'ensemble des données (glimpse) avec un résumé rapide de chaque variable (summary) 
```

```{r}
#Description des données :

#à faire

#Objectif de l'analyse : 

#à faire
```

```{r étude variable quantitative}
# 1. Indicateurs synthétiques
analyse_social_interaction <- data.frame(
  Indicateur = c("N", "Moyenne", "Médiane", "Écart-type", "Minimum", "Maximum", "asymétrie", "Aplatissement"),
  Valeur = c(
    length(teens$Social_Interactions),
    mean(teens$Social_Interactions),
    median(teens$Social_Interactions),
    sd(teens$Social_Interactions),
    min(teens$Social_Interactions),
    max(teens$Social_Interactions),
    skewness(teens$Social_Interactions),
    kurtosis(teens$Social_Interactions)
  )
)
print(analyse_social_interaction)

# 2. Histogramme
ggplot(teens, aes(x = Social_Interactions)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black", aes(y = ..density..)) +
  geom_density(alpha = .2, fill = "#FF6666") +
  labs(title = "Distribution des Interactions Sociales", x = "Niveau d'interactions", y = "Densité")

# 3. Boxplot
ggplot(teens, aes(y = Social_Interactions)) +
  geom_boxplot(fill = "lightgreen") +
  labs(title = "Boxplot des Interactions Sociales", y = "Niveau d'interactions")

#Interprétation :

    #Tendance centrale : Le niveau moyen d'interactions sociales se situe au milieu de l'échelle .

    #Dispersion : L'écart-type de 3,14 montre une dispersion modérée. Le Boxplot confirme l'absence de valeurs aberrantes.

    #Conclusion : La variable Social_Interactions suit une distribution proche d'une loi uniforme discrète. Il n'y a pas de groupe dominant, les adolescents de cet échantillon se répartissent de manière assez égale sur tous les niveaux d'interaction sociale possible. Cela suggère que dans ce dataset, l'abondance d'interactions sociales n'est pas polarisé.
```



#analyse bivariée pour contredire le mythe du gaming pour les mecs et des réseaux pour les meufs
```{r analyse bivariée entre gender et phone purpose}

# Tableau des effectifs
table_croisee <- table(teens$Gender, teens$Phone_Usage_Purpose)
print("--- Tableau de contingence (Effectifs) ---")
print(table_croisee)

# Tableau des pourcentages en ligne (Profils par genre)
prop_table <- prop.table(table_croisee, 1) * 100
print("--- Profils en lignes (Pourcentages par genre) ---")
print(round(prop_table, 2))

# Test d'indépendance du Chi-2
test_chi2 <- chisq.test(table_croisee)
print(test_chi2)



ggplot(teens, aes(x = Gender, fill = Phone_Usage_Purpose)) +
  geom_bar(position = "fill") + # "fill" pour avoir des barres de même hauteur (100%)
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(title = "Répartition de l'usage du téléphone selon le genre",
       x = "Genre",
       y = "Proportion",
       fill = "Usage") +
  scale_fill_brewer(palette = "Pastel1")


```

```{r régression linéaire entre Interaction / Perf}
model <- lm(Social_Interactions ~ Academic_Performance, teens)

ggplot() + geom_qq(aes(sample = rstandard(model))) + geom_abline(color = "red")
hist(model$residuals)
```
