---
title: "projet fifa"
output: html_document
date: "2026-04-27"
---

```{r packages}
p_load <- pacman::p_load
p_load(readr)            #pour importer nos données
p_load(tidyverse)        #pour les fonctions essentielles (ggplot,...)
p_load(questionr)        #pour les tables statistiques
p_load(Epi)              #pour les tables statistiques aussi
p_load(vtable)           #pour de meilleures tables statistiques
p_load(patchwork)        #c'est pour mieux présenter les graphiques, il laisse plus de choix que simplement grid.arrange()
p_load(ggplot2)
p_load(e1071) # Pour l'asymétrie et l'aplatissement
p_load(readxl)
```

```{r file fusion du .xlsx}
path <- "Career Mode female player datasets - FIFA 16-22.xlsx"

# lister les noms de tous les onglets présents dans le fichier
onglets <- excel_sheets(path)

# map_df va appliquer la lecture à chaque nom d'onglet
# .id donne une colonne pour les différents fifa genre "FIFA 22"
fifa <- onglets %>% set_names() %>%
  map_df(~ read_excel(path, sheet = .x), .id = "annee_fifa")
```

```{r}
fifa_clean <- fifa %>% 
  select(c("annee_fifa", "long_name", "player_positions", "overall", "potential", "age", "height_cm", "weight_kg", "nationality_name", "preferred_foot", "weak_foot", "skill_moves", "preferred_foot", "weak_foot", "skill_moves","pace", "shooting", "passing", "dribbling", "defending", "physic", "mentality_aggression" ,"mentality_interceptions" , "mentality_positioning", "mentality_vision", "mentality_penalties"))      #on retire les variables qu'on juge redondantes ou "néfastes" (vides)
#on pourrait faire na.omit, mais il y a un risque chaque ligne contienne des données manquantes, on vérifie
head(fifa_clean)
```

```{r affichage données}
head(fifa_clean)    #affiche les six premières lignes
glimpse(fifa)       #affiche les données de chaque variable en condensé
summary(fifa)       #fait un résumé de chaque variable
spec(fifa)
#petite vue d'ensemble des données (glimpse) avec un résumé rapide de chaque variable (summary) 
```

I - Analyse univariée d'une variable quantitative continue : overall

Nous allons faire une analyse de overall, qui est une note générale de chaque joueuse, en étudiant sa distribution.

```{r}
fifa_clean %>%                   #on part de l'intégralité de la base de données
  select(overall) %>%              #on garde unique la colonne qui correspond aux notes overall
  filter(!is.na(overall)) %>%      #on retire les possibles données manquantes, bien que ce soit peu probable puisqu'on a déjà fait na.omit en nettoyant la base de données
  summary() %>%                 #cette fonction calcule des données essentielles pour comprendre la variable, que l'on exploitera plus bas
  kable()                       #et enfin, on met bien en forme avec kable, qui nous fait un tableau propre
```
